// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_S.Context;

namespace Prueba_S.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prueba_S.Models.Cliente", b =>
                {
                    b.Property<string>("CodCliente")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NomCliente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Prueba_S.Models.Producto", b =>
                {
                    b.Property<string>("CodProducto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NomProducto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Prueba_S.Models.Venta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClienteCodCliente")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProductoCodProducto")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("ClienteCodCliente");

                    b.HasIndex("ProductoCodProducto");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Prueba_S.Models.Venta", b =>
                {
                    b.HasOne("Prueba_S.Models.Cliente", "Cliente")
                        .WithMany("ventas")
                        .HasForeignKey("ClienteCodCliente");

                    b.HasOne("Prueba_S.Models.Producto", "Producto")
                        .WithMany("ventas")
                        .HasForeignKey("ProductoCodProducto");

                    b.Navigation("Cliente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Prueba_S.Models.Cliente", b =>
                {
                    b.Navigation("ventas");
                });

            modelBuilder.Entity("Prueba_S.Models.Producto", b =>
                {
                    b.Navigation("ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
